config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :schools
  resources :programs
  resources :students

  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :student
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :school
  belongs_to :student
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
  has_many :reports
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :reports
  has_many :programs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:morn_insp, :even_ins, :night_ins, :student_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:student_name, :maths_mark, :eng_mark, :kis_mark, :school_id, :student_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :location)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :code, :school, :gender, :location, :disability)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kenscouts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programs/_form.html.erb
<%= form_with(model: program, local: true) do |form| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :morn_insp %>
    <%= form.text_field :morn_insp %>
  </div>

  <div class="field">
    <%= form.label :even_ins %>
    <%= form.text_field :even_ins %>
  </div>

  <div class="field">
    <%= form.label :night_ins %>
    <%= form.text_field :night_ins %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programs</h1>

<table>
  <thead>
    <tr>
      <th>Morn insp</th>
      <th>Even ins</th>
      <th>Night ins</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.morn_insp %></td>
        <td><%= program.even_ins %></td>
        <td><%= program.night_ins %></td>
        <td><%= program.student %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Morn insp:</strong>
  <%= @program.morn_insp %>
</p>

<p>
  <strong>Even ins:</strong>
  <%= @program.even_ins %>
</p>

<p>
  <strong>Night ins:</strong>
  <%= @program.night_ins %>
</p>

<p>
  <strong>Student:</strong>
  <%= @program.student %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_name %>
    <%= form.text_field :student_name %>
  </div>

  <div class="field">
    <%= form.label :maths_mark %>
    <%= form.number_field :maths_mark %>
  </div>

  <div class="field">
    <%= form.label :eng_mark %>
    <%= form.number_field :eng_mark %>
  </div>

  <div class="field">
    <%= form.label :kis_mark %>
    <%= form.number_field :kis_mark %>
  </div>

  <div class="field">
    <%= form.label :school_id %>
    <%= form.text_field :school_id %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Student name</th>
      <th>Maths mark</th>
      <th>Eng mark</th>
      <th>Kis mark</th>
      <th>School</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.student_name %></td>
        <td><%= report.maths_mark %></td>
        <td><%= report.eng_mark %></td>
        <td><%= report.kis_mark %></td>
        <td><%= report.school %></td>
        <td><%= report.student %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student name:</strong>
  <%= @report.student_name %>
</p>

<p>
  <strong>Maths mark:</strong>
  <%= @report.maths_mark %>
</p>

<p>
  <strong>Eng mark:</strong>
  <%= @report.eng_mark %>
</p>

<p>
  <strong>Kis mark:</strong>
  <%= @report.kis_mark %>
</p>

<p>
  <strong>School:</strong>
  <%= @report.school %>
</p>

<p>
  <strong>Student:</strong>
  <%= @report.student %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.location %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @school.location %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code %>
  </div>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field :school %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.check_box :gender %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :disability %>
    <%= form.check_box :disability %>
  </div>

  <div class="field">
    <%= form.label :school_id %>
    <%= form.text_field :school_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>School</th>
      <th>Gender</th>
      <th>Location</th>
      <th>Disability</th>
      <th>School</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.code %></td>
        <td><%= student.school %></td>
        <td><%= student.gender %></td>
        <td><%= student.location %></td>
        <td><%= student.disability %></td>
        <td><%= student.school %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @student.code %>
</p>

<p>
  <strong>School:</strong>
  <%= @student.school %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.gender %>
</p>

<p>
  <strong>Location:</strong>
  <%= @student.location %>
</p>

<p>
  <strong>Disability:</strong>
  <%= @student.disability %>
</p>

<p>
  <strong>School:</strong>
  <%= @student.school %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>